<?php
$nombreGeneral = "Group challenges";
define("litMenuInicio", 'Home');
define("litMenuIniciarSesion", 'Log in');
define("litMenuRegistrarse", 'Register');
define("litMenuMiPerfil", 'My profile');
define("litMenuNuevoRetoPeso", 'New challenge');
define("litMenuMisGrupos", 'My challenges');
define("litMenuMisPesos", 'My weights');
define("litMenuNuevoPeso", 'New weight');
define("litMenuNuevoDato", 'New data');
define("litMenuMisDatos", 'My data');
define("litMenuNuevoRetoOtros", 'New challenge');
define("litMenuOtrosGrupos", 'My challenges');
define("litMenuSalir", 'Log out');
define("litMenuRetosPeso", 'Weight challenges');
define("litMenuOtrosRetos", 'Other challenges');
define("litEnviarDatos", 'Submit data');
define("litKeywords", 'Group weight challenge');
define("litDescri", 'Weight challenge among friends by creating groups');
define("litIniciarSesion", 'Log in');
define("litRegistrarse", 'Register');
define("litCambiosOk", 'Changes saved successfully.');
define("litError1", 'An error has occurred');
define("litError2", 'If you wish, you can contact the administrator at <a href="mailto:%1$s">%1$s</a>');
define("litErrorExisteUser", 'A user with the provided email already exists.');
define("litRegistroOk1", 'Registration created successfully.');
define("litRegistroOk2", 'A verification link has been sent to your email inbox.');
define("litEstimado", 'Dear %1$s.');
define("litAtentamente", 'Sincerely,');
define("litEmailVerifSubject", 'Verify your email address');
define("litEmailVerif01", 'Welcome to the website for group or individual challenges.');
define("litEmailVerif02", 'Click the following link to validate your email inbox:');
define("litCampoOblig", 'The field %1$s is required');
define("litPaswwordKo", 'Passwords do not match');
define("litUsoKo", 'You must accept the terms of use');
define("litMail", 'Email');
define("litNombrePersona", 'First name');
define("litApellidos", 'Last name');
define("litIdioma", 'Language');
define("litUnidad", 'Unit');
define("litMostrarPeso", 'Show weight');
define("litMostrarPesoDemas", 'Show weight to others');
define("litPassword", 'Password');
define("litPasswordRepetir", 'Repeat password');
define("litPasswordNew", 'Password');
define("litPasswordNewRepetir", 'Repeat password');
define("litPasswordVacioNoCambio", 'Leave blank to keep current password');
define("litRelleneFormReg", 'Or fill out the following form to register');
define("litSi", 'Yes');
define("litNo", 'No');
define("litNoPorcen", 'No (Only the percentage of weight gain or loss will be shown)');
define("litAceptoUso", 'I accept the <a href="%1$s" target="_blank">terms of use</a>');
define("litMiPerfil", 'My profile');
define("litPerfilOk", 'Your profile has been successfully updated.');
define("litMailExiste", 'Email already exists.');
define("litCambiarPerfil", 'Edit my profile');
define("litNoCambiarPass", 'If you don’t want to change your password, leave it blank. After making the desired changes, click "'.litEnviarDatos.'"');
define("litFormaVida", 'A way of life. A way of group challenges.');
define("litBienvenido", 'Welcome to <strong>%1$s</strong>!');
define("litBienvenido01", 'On this website, you can create groups to track the challenges you do with your friends.');
define("litBienvenido02", 'You can create all kinds of challenges, as long as they can be measured numerically (e.g., steps taken in a day) or with a "yes" or "no" (e.g., indicating whether you exercised on a given day).');
define("litBienvenido03", 'On this website, you can create groups to track who is losing the most weight. You can also create weight-related challenges (to see who loses more weight, either in absolute terms or by percentage).');
define("litIntimidad", 'Privacy');
define("litIntimidad01", 'If you wish, you can configure a group so that weights are hidden and only the percentage of weight gain or loss is shown for each member.');
define("litAceptInvitacion", '%1$s has accepted the invitation to group %2$s.');
define("litRechazadoInvitacion", '%1$s has declined the invitation to group %2$s.');
define("litInvitacionSubject", 'Invitation from %1$s ');
define("litInvitacionSubject", '%1$s’s answer to a weight challenge group invitation');
define("litInvitacionRechazada", 'Invitation successfully declined');
define("litRechazarInvitacionTitle", 'Decline invitation');
define("litInicioSesionKo01", 'Login failed.');
define("litInicioSesionKo02", 'Your email and password do not match any account.');
define("litEnhorabuena", 'Congratulations!');
define("litVerifMailOk", 'Your email has been successfully verified. Log in using the following link:');
define("litEnlaceKo01", 'Invalid link.');
define("litEnlaceKo02", 'Sorry, the link did not work. You may have received it more than two hours ago. Please copy and paste the link and try again. You can also request a new one here: <a href="mailto:%1$s">%1$s</a>');
define("litInicioSesion01", 'Login required.');
define("litInicioSesion02", 'You must log in to access your data.');
define("litEnlaceCaducado01", 'Expired link.');
define("litEnlaceCaducado02", 'Sorry, the link you used is no longer valid.');
define("litLogin", 'Login');
define("litIntroDatosAcceso", 'Enter your login details');
define("litOlvidoPass", 'Forgot your password?');
define("litRecordarme", 'Remember me');
define("litRegistrarseNuevo", 'Register as a new user');
define("litEntrar", 'Enter');
define("litBorrarGrupoNoAdmin01", 'You cannot delete the group because you are not the group administrator.');
define("litBorrarGrupoNoAdmin02", 'Please contact a group administrator if you wish to delete it.');
define("litMisGrupos", 'My challenges');
define("litMisOtrosGrupos", 'My other groups');
define("litMisOtrosGrupos01", 'Here you can manage other challenge groups not related to weight.');
define("litSeguroElimGrupo", 'Are you sure you want to delete this group?');
define("litInvitacionesPendientes", 'Pending invitations');
define("litIconoVerdeRojo", 'Click the green or red icon to accept or decline joining the group.');
define("litFechaInicio", 'Start date');
define("litFechaInicioFin", 'Start - End date');
define("litFechaFin", 'End date');
define("litMiembros", 'Members');
define("litAceptarInvitacion", 'Accept invitation');
define("litRechazarInvitacion", 'Decline invitation');
define("litAceptarInvitacionConfirm", 'Are you sure you want to ACCEPT the invitation?');
define("litRechazarInvitacionConfirm", 'Are you sure you want to DECLINE the invitation?');
define("litCrearNuevoGrupo", 'Create new group');
define("litReordenarColumnas", 'Click on the column names to sort by them.');
define("litModificar", 'Edit');
define("litSalirGrupo", 'Leave group');
define("litMiembrosGrupo", 'Members of group %1$s');
define("litSeguroEliminar", 'Are you sure you want to remove ');
define("litNuevoMiembro", 'New member');
define("litRol", 'Role');
define("litBorrar", 'Delete');
define("litVolver", 'Back');
define("litMisPesos", 'My weights');
define("litConfirmElimPeso", 'Are you sure you want to delete this weight?');
define("litFecha", 'Date');
define("litHora", 'Time');
define("litPeso", 'Weight');
define("litComentario", 'Comment');
define("litNuevoGrupo", 'New group');
define("litPeriodoPesajes", 'Weigh-in interval');
define("litCrearNuevoGrupoTitle", 'Create a new group');
define("litMailBienvenido01", 'Welcome to the group challenge site.');
define("litMailBienvenido02", '%1$s has invited you to join group "%2$s" to take on this challenge together.');
define("litMailBienvenido03", 'To ACCEPT joining the group, click the following link:');
define("litMailBienvenido04", 'To DECLINE joining the group, click the following link:');
define("litMailBienvenidoSubject", 'Invitation from %1$s to a challenges group');
define("litNuevoMiembroGrupo", 'New member for group %1$s');
define("litAnadirMiembroGrupo", 'Add member to group %1$s');
define("litAnadirMiembroYaAmigo", 'You can choose it from the list of people you already have challenges with.:');
define("litAnadirMiembroNuevo", 'Or invite a new person:');
define("litNuevoPeso", 'New weight');
define("litIntroNuevoPeso", 'Enter new weight');
define("litPassChangeOk", 'Your password has been successfully changed. <a href="/login/en">Log in</a>');
define("litCambiarPass01", 'Change password');
define("litCambiarPass02", 'Change your password by filling out the following form');
define("litNuevaPass", 'New password');
define("litRepeNuevaPass", 'Repeat new password');
define("litReinicarPass", 'Reset password');
define("litIrInicioSesion", 'Go to the page where you can log in');
define("litVuelvaIntentar", 'Please try again');
define("litCambioPassMail01", 'Please click here within 2 hours to change your password:');
define("litCambioPassMailSubject", 'Change your password');
define("litEnlaceEnviado01", 'Link sent');
define("litEnlaceEnviado02", 'We just sent you an email with a link to change your password. Please change it within two hours.');
define("litDescriReto", 'Challenge Description');
define("litReto", 'Challenge');
define("litEvoluPeso", 'My weight evolution');
define("litEstadisticas", 'Statistics');
define("litEstadGrupo", 'Group %1$s statistics');
define("litEstadGrupoAcum", 'Cumulative graph of group %1$s');
define("litEstadGrupoReal", 'Individual data of group %1$s');
define("litMedia", 'Average %1$s');
define("litDiario", 'Daily');
define("litSemanal", 'Weekly');
define("litMensual", 'Monthly');
define("litAdministrador", 'Administrator');
define("litUsuario", 'User');
define("litMailRecordatorioSubject", 'Reminder: You’re late logging your data for the challenges');
define("litMailRecordatorio01", 'We remind you that you haven’t logged your challenge data about active groups you are part of on our website.');
define("litMailRecordatorio02", 'Please click the link of each group, and record your data as soon as possible.');
define("litEvolucionPorcentual", 'Percentage evolution');
define("litEvolucionPesoReal", 'Actual weight evolution');
define("litEvolucionCambiosPeso", 'Weight change evolution');
define("litPreguntaIntro", 'Question when entering data');
define("litTipoRespuesta", 'Type of data to enter');
define("litNuevoDato", 'New data');
define("litIntroNuevoDato", 'Enter new data');
define("litPrimeroGrupo", 'First select a group');
define("litDato", 'Data');
define("litEvoluDatos", 'My data evolution');
define("litGrupo", 'Group');
define("litQuienGana", 'Who wins?');
define("litQuienGanaMas", 'The one who scores the most');
define("litQuienGanaMenos", 'The one who scores the least');
define("litQuienGanaMediaMas", 'The one who scores the best average');
define("litQuienGanaMediaMenos", 'The one who scores the worst average');
define("litPeriodoDatos", 'Period between data entry');
define("litAyudaPregunta", 'For example, in a challenge to see who takes the most steps, the question to enter data would be:\n\nHow many steps have you taken?');
define("litNombreGrupo", 'Name of the group');
define("litNombreReto", 'Name of the challenge');
define("litNombre", 'Name');
define("litRespuestaNumericos", 'Numeric');
define("litRespuestaSiNoSi", '"Yes" and "No", where the "Yes" is the good thing');
define("litRespuestaSiNoNo", '"Yes" and "No", where the "No" is the good thing');
define("litAyudaRespuesta", '- '.litRespuestaNumericos.': In a challenge to see who takes the most steps, each time data is entered, the NUMBER OF STEPS taken would be entered.\n\n- '.litRespuestaSiNoSi.': In a challenge to see who exercises the most days, what GIVES POINTS is ANSWERING YES to the question "Have you exercised today?"\n\n- '.litRespuestaSiNoNo.': In a challenge to see who smokes the fewest days, what GIVES POINTS is ANSWERING NO to the question "Have you smoked today?"');
define("litIniciaGoogle", 'Sign in with Google');
define("litIntroduceDatosAcceso", 'Or enter your sign in details:');
define("litVerOpciones", 'View options');
define("litVerDetalles", 'View details');
define("litDetallesGrupo", 'Group details');
define("litModificarGrupo", 'Group modify');
define("litMenuRetosAcciones", 'Action challenges');
define("litMenuNuevoRetoAcciones", 'New challenge');
define("litGestionarAcciones", 'Manage actions');
define("litVerAcciones", 'View actions');
define("litGestionarAccionesGrupo", 'Manage actions for group %1$s');
define("litNombreAccion", 'Action name');
define("litImportanciaAccion", 'Importance (from 1 to 100)');
define("litAccionesGrupo", 'Actions for group %1$s');
define("litNuevaAccion", 'Create new action');
define("litNuevaAccionGrupo", 'New action for group %1$s');
define("litBorrar", 'Delete');
define("litSeguroElimAccion", 'Are you sure you want to delete this action?');
define("litErrorMas100", 'The value cannot be greater than 100.');
define("litNuevoDatoGrupo", 'New data for group %1$s');
define("litMarcaAcciones", 'Mark the actions you have completed:');
define("litMarcaAccionesOblig", 'You must mark at least one action. If you haven’t completed any, simply don’t save any data for this day.');
?>
