<?php
define("litMenuInicio", 'Inicio');
define("litMenuIniciarSesion", 'Iniciar sesion');
define("litMenuRegistrarse", 'Registrarse');
define("litMenuMiPerfil", 'Mi perfil');
define("litMenuMisGrupos", 'Mis grupos');
define("litMenuMisPesos", 'Mis pesos');
define("litMenuNuevoPeso", 'Nuevo peso');
define("litMenuSalir", 'Salir');
define("litKeywords", 'Reto peso grupos');
define("litDescri", 'Reto de peso entre amigos creando grupos');

define("litRegistrarse", 'Registrarse');
define("litCambiosOk", 'Cambios guardados correctamente.');
define("litError1", 'Ha ocurrido un error');
define("litError2", 'Si lo desea, puede ponerse en contacto con el administrador en <a href="mailto:%1$s">%1$s</a>');
define("litErrorExisteUser", 'Ya existe un usuario registrado con el email que ha indicado.');
define("litRegistroOk1", 'Registro creado correctamente.');
define("litRegistroOk2", 'Se ha enviado un enlace de verificación a su buzón de email.');
define("litEstimado", 'Estimad@ %1$s.');
define("litAtentamente", 'Atentamente,');
define("litEmailVerifSubject", 'Verifique su direccion de email');
define("litEmailVerif01", 'Bienvenid@ al reto de peso en grupo.');
define("litEmailVerif02", 'Presione el siguiente enlace para validar su buzon de email:');
define("litCampoOblig", 'El campo %1$s es obligatorio');
define("litPaswwordKo", 'No ha repetido bien la contraseña');
define("litUsoKo", 'Debe aceptar las condiciones de uso');
define("litMail", 'Email');
define("litNombre", 'Nombre');
define("litApellidos", 'Apellidos');
define("litIdioma", 'Idioma');
define("litUnidad", 'Unidad');
define("litMostrarPeso", 'Mostrar peso');
define("litMostrarPesoDemas", 'Mostrar peso a los demás');
define("litPassword", 'Contraseña');
define("litPasswordRepetir", 'Repetir contraseña');
define("litPasswordNew", 'Contraseña');
define("litPasswordNewRepetir", 'Repetir contraseña');
define("litPasswordVacioNoCambio", 'Dejar vacío para no cambiarla');
define("litRelleneFormReg", 'Rellene el siguiente formulario para registrarse');
define("litSi", 'Sí');
define("litNo", 'No');
define("litNoPorcen", 'No (Solo se mostrará el porcentaje de subida o bajada)');
define("litAceptoUso", 'Acepto las <a href="%1$s" target="_blank">condiciones de uso</a>');
define("litEnviarDatos", 'Enviar datos');
define("litMiPerfil", 'Mi perfil');
define("litPerfilOk", 'Su perfil se ha actualizado correctamente.');
define("litMailExiste", 'El Email ya existe.');
define("litCambiarPerfil", 'Cambiar mi perfil');
define("litNoCambiarPass", 'Si no desea cambiar su contraseña, déjela vacía. Después de hacer los cambios deseados, presione en "Guardar"');
define("litFormaVida", 'Una forma de vida. Una forma de comer.');
define("litBienvenido", '¡Bienvenido a <strong>%1$s</strong>!');
define("litBienvenido01", 'En esta web podrás crear grupos con los que llevar un control sobre quien va adelgazando más.');
define("litIntimidad", 'Intimidad');
define("litIntimidad01", 'Si lo deseas, puedes configurar un grupo para que no se muestren los pesos, y solo se muestre el porcentaje de subida o bajada de peso de cada componente del grupo.');
define("litAceptInvitacion", '%1$s ha aceptado la invitación al grupo %2$s.');
define("litRechazadoInvitacion", '%1$s ha rechazado la invitación al grupo %2$s.');
define("litInvitacionSubject", 'Respuesta de %1$s a su invitación al grupo de reto de peso');
define("litInvitacionRechazada", 'Invitación rechazada correctamente');
define("litRechazarInvitacionTitle", 'Rechazar invitación');
define("litInicioSesionKo01", 'Inicio de sesión erroneo.');
define("litInicioSesionKo02", 'Su email y contraseña no coinciden con ninguna cuenta.');
define("litEnhorabuena", '¡Enhorabuena!');
define("litVerifMailOk", 'Ha verificado correctamente su email. Inicie sesión pulsando en el siguiente enlace:');
define("litEnlaceKo01", 'Enlace erroneo.');
define("litEnlaceKo02", 'Disculpe, pero el enlace no ha funcionado. Quizá lo recibió hace más de dos horas. Por favor, copie y pegue el enlace y vuelva a intentarlo. También puede recibir uno nuevo aquí: <a href="mailto:%1$s">%1$s</a>');
define("litInicioSesion01", 'Inicio de sesión requerido.');
define("litInicioSesion02", 'Es necesario iniciar sesión para acceder a sus datos.');
define("litEnlaceCaducado01", 'Enlace caducado.');
define("litEnlaceCaducado02", 'Disculpe, pero el enlace que has usado ya no es válido.');
define("litLogin", 'Login');
define("litIntroDatosAcceso", 'Introduzca sus datos de acceso');
define("litOlvidoPass", '¿Olvidó su contraseña?');
define("litRecordarme", 'Recordarme');
define("litRegistrarseNuevo", 'Registrarse como nuevo usuario');
define("litEntrar", 'Entrar');
define("litBorrarGrupoNoAdmin01", 'No puede borrar el grupo porque no es administrador del grupo.');
define("litBorrarGrupoNoAdmin02", 'Por favor, contacte con un administrador del grupo si desea borrarlo.');
define("litMisGrupos", 'Mis grupos');
define("litSeguroElimGrupo", '¿Está seguro de que desea eliminar este grupo?');
define("litInvitacionesPendientes", 'Invitaciones pendientes');
define("litIconoVerdeRojo", 'Pulsa el icono verde o rojo para aceptar o rechazar entrar en el grupo.');
define("litFechaInicio", 'Fecha inicio');
define("litFechaFin", 'Fecha fin');
define("litMiembros", 'Miembros');
define("litAceptarInvitacion", 'Aceptar invitación');
define("litRechazarInvitacion", 'Rechazar invitación');
define("litAceptarInvitacionConfirm", '¿Está seguro que desea ACEPTAR la invitación?');
define("litRechazarInvitacionConfirm", '¿Está seguro que desea RECHAZAR la invitación?');
define("litCrearNuevoGrupo", 'Crear nuevo grupo');
define("litReordenarColumnas", 'Pulsa sobre el nombre de las columnas si quieres reordenar por ellas.');
define("litModificar", 'Modificar');
define("litSalirGrupo", 'Salir del grupo');
define("litMiembrosGrupo", 'Miembros del grupo %1$s');
define("litSeguroEliminar", '¿Está seguro de que desea eliminar a ');
define("litNuevoMiembro", 'Nuevo miembro');
define("litRol", 'Rol');
define("litBorrar", 'Borrar');
define("litVolver", 'volver');
define("litMisPesos", 'Mis pesos');
define("litConfirmElimPeso", '¿Está seguro de que desea eliminar este peso?');
define("litFecha", 'Fecha');
define("litPeso", 'Peso');
define("litComentario", 'Comentario');
define("litNuevoGrupo", 'Nuevo grupo');
define("litPeriodoPesajes", 'Periodo entre pesajes');
define("litCrearNuevoGrupoTitle", 'Crear un grupo nuevo');
define("litMailBienvenido01", 'Bienvenid@ al reto de peso en grupo.');
define("litMailBienvenido02", '%1$s le invitado a participar en el grupo %2$s para hacer juntos el reto del peso.');
define("litMailBienvenido03", 'Para ACEPTAR entrar en su grupo, presione el siguiente enlace:');
define("litMailBienvenido04", 'Para RECHAZAR entrar en su grupo, presione el siguiente enlace:');
define("litMailBienvenidoSubject", 'Invitación de %1$s a un grupo de reto de peso');
define("litNuevoMiembroGrupo", 'Nuevo miembro para el grupo %1$s');
define("litAnadirMiembroGrupo", 'Añadir miembro al grupo %1$s');
define("litNuevoPeso", 'Nuevo peso');
define("litIntroNuevoPeso", 'Introducir nuevo peso');
define("litPassChangeOk", 'La contraseña se ha cambiado correctamente. <a href="/login">Iniciar sesión</a>');
define("litCambiarPass01", 'Cambiar contraseña');
define("litCambiarPass02", 'Cambie su contraseña rellenando el siguiente formulario');
define("litNuevaPass", 'Nueva contraseña');
define("litRepeNuevaPass", 'Repetir nueva contraseña');
define("litReinicarPass", 'Reiniciar contraseña');
define("litIrInicioSesion", 'Ir a la página donde Iniciar sesión');
define("litVuelvaIntentar", 'Vuelva a intentarlo');
define("litCambioPassMail01", 'Por favor, presione aqui antes de 2 horas para cambiar su contraseña:');
define("litCambioPassMailSubject", 'Cambie su contraseña');
define("litEnlaceEnviado01", 'Enlace enviado');
define("litEnlaceEnviado02", 'Le acabamos de enviar un email con un enlace para que cambie su contraseña. Por favor, cámbiela antes de dos horas');
define("litDescriReto", 'Descripción del reto');
define("litReto", 'Reto');
define("litEvoluPeso", 'Evolución de mi peso');
define("litEstadisticas", 'Estadísticas');
define("litEstadGrupo", 'Estadísticas del grupo %1$s');
define("litDiario", 'Diario');
define("litSemanal", 'Semanal');
define("litMensual", 'Mensual');
define("litAdministrador", 'Administrador');
define("litUsuario", 'Usuario');

define("litMailRecordatorioSubject", 'Recordatorio retraso en tu pesada para el reto');
define("litMailRecordatorio01", 'Le recordamos que le ha faltado guardar su peso en nuestra web, dado que está en los siguientes grupos que están activos:');
define("litMailRecordatorio02", 'Por favor, haga clik en el siguiente enlace, inicie sesión y guarde su peso cuanto antes:');
?>